language: csharp
dotnet: 5.0
dist: bionic
mono: none
sudo: required
services:
    - docker
   
branches:
    only:
        - master
        
env:
    global:
        - DOTNET_CLI_TELEMETRY_OPTOUT: 1

install:
  - dotnet restore

before_script:
    - curl https://cli-assets.heroku.com/install.sh | sudo sh
    - docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com

script:
    - 'if [[ "$TRAVIS_BRANCH" == "master" ]] && [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then docker build -f MedievalIo.Web/Dockerfile -t registry.heroku.com/$HEROKU_APP/web . ; fi'

deploy:   
    provider: script
    script: 
        docker push registry.heroku.com/$HEROKU_APP/web;
        heroku container:release web --app $HEROKU_APP
    on:
        branch: master